### PR TITLE
Added LemLib library and split config into robot-config.cpp (PASSED BUILD)

### LINKED ISSUE #2: LemLib Integration

### PR DESCRIPTION
**Pull request by LycoKodo**
Added LemLib library and split config into robot-config.cpp (PASSED PROS BUILD)

### CODE REVIEW

**Review by outsidermm — CHANGES_REQUESTED** [review]
I think we should purpose this pr js to integrate lemlib on pr1
we can test my branch then on pr2 
then refactor pro api to lemlib on pr3
sounds cleaner lmk what u think

**Comment by LycoKodo** [comment]
> my

Yeah I think thats a good idea. I mean my fork wasn't much other than applying LemLib and some minor refactoring.

**Comment by outsidermm** [comment]
> > my
> 
> Yeah I think thats a good idea. I mean my fork wasn't much other than applying LemLib and some minor refactoring.

just delete the change u made to robot_config, js pure lemlib thanks

**Comment by LycoKodo** [comment]
@outsidermm  I have made the requested changes. Please review them when you have a moment. Thank you!

**Review by LycoKodo — COMMENTED** [review]
Please ignore this

**Review by LycoKodo — COMMENTED** [review]
@outsidermm I have made the requested changes. Please review them when you have a moment. Thank you!

**Review by outsidermm — APPROVED** [review]
LGTM

**Pull request merged**
